import Head from 'next/head'

import mapboxgl from 'mapbox-gl/dist/mapbox-gl-csp';
import MapboxWorker from 'worker-loader!mapbox-gl/dist/mapbox-gl-csp-worker';
import {createRef, useEffect} from "react";

mapboxgl.accessToken = ''
export default function Home() {
    mapboxgl.workerClass = MapboxWorker; // Wire up loaded worker to be used instead of the default

    const map = createRef()
    const mapContainer = createRef()

    useEffect(() => {
        if (map.current) return;
        map.current = new mapboxgl.Map({
            container: mapContainer.current, // container ID
            style: 'mapbox://styles/mapbox/streets-v11', // style URL
            center: [-74.5, 40], // starting position [lng, lat]
            zoom: 9 // starting zoom
        })
    })

    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
            </Head>
            <div id="map" ref={mapContainer}></div>
        </div>
    )
}
